### ISSUE TITLE
Omni-bot fails to load

### ISSUE THREAD

**Issue by rfdparker** [flathub/com.etlegacy.ETLegacy#2]
Omni-bot fails to load.

This issue appears to occur with Flatpak but not with the game installed 'conventionally' (i.e. using 32-bit installer on 64-bit OS rather than Flatpak).

## Steps to reproduce

1. Launch game
2. If first run, answer initial config questions
3. Host a game
4. Leave the limbo menu
4. Press escape, choose **Referee** » **Bots**
5. Chose numbers of bots, click **Bots on** etc but observe that no bots join the game
6. In console, observe `Omni-bot not loaded.` message(s)
7. Exit/close game

If steps are repeated after the first run, the following can also be found in the console after beginning to host a game:

```
0 Omni-bot: LoadLibrary Failed with Error: legacy/omni-bot/omnibot_et.so: cannot open shared object file: No such file or directory
0 Omni-bot: Looking for legacy/omni-bot/omnibot_et.so, not found
0 Omni-bot: LoadLibrary Failed with Error: ./omnibot_et.so: cannot open shared object file: No such file or directory
0 Omni-bot: Looking for ./omnibot_et.so, not found
0 Omni-bot: LoadLibrary Failed with Error: /home/rfdparker/omni-bot/omnibot_et.so: cannot open shared object file: No such file or directory
0 Omni-bot: Looking for /home/rfdparker/omni-bot/omnibot_et.so, not found
0 Omni-bot: LoadLibrary Failed with Error: omnibot_et.so: cannot open shared object file: No such file or directory
0 Omni-bot: Looking for omnibot_et.so, not found
0 Unable to Initialize Omni-Bot
0 Omni-Bot Initialization completed in 0.00 seconds
```

## Workaround

After launching the game, prior to hosting a game, in the game's console run:

```
\omnibot_path "/app/bin/legacy/omni-bot"
```

After this is run once, it appears to be saved in `~/.var/app/com.etlegacy.ETLegacy/.etlegacy/legacy/profiles/Rob/etconfig.cfg`.

## Environment info

I am running version 2.77.1 (commit c5b5a5081df6a6d28df781a690e74a0a355e07b64a91f3a9e8b0511114a1afb2) on Ubuntu 20.04 LTS on an `amd64` architecture CPU. Flatpak is 1.6.5 is installed the Ubuntu repo.

```
$ flatpak info com.etlegacy.ETLegacy

ET: Legacy - ET: Legacy is an open source project based on the code of
Wolfenstein: Enemy Territory which was released in 2010 under the terms of the
GPLv3.

          ID: com.etlegacy.ETLegacy
         Ref: app/com.etlegacy.ETLegacy/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 2.77.1
     License: GPL-3.0-or-later
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 146.0 MB
     Runtime: org.freedesktop.Platform/x86_64/20.08
         Sdk: org.freedesktop.Sdk/x86_64/20.08

      Commit: c5b5a5081df6a6d28df781a690e74a0a355e07b64a91f3a9e8b0511114a1afb2
      Parent: 551de63b64140bb5c63f9c527a3edd09085785a61471c22017c35d317d84896a
     Subject: Significantly improved base package with additional metadata (d159127e)
        Date: 2021-03-20 08:23:19 +0000

$ flatpak --version
Flatpak 1.6.5

$ apt policy flatpak 
flatpak:
  Installed: 1.6.5-0ubuntu0.3
  Candidate: 1.6.5-0ubuntu0.3
  Version table:
 *** 1.6.5-0ubuntu0.3 500
        500 http://gb.archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages
        500 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages
        100 /var/lib/dpkg/status
     1.6.3-1 500
        500 http://gb.archive.ubuntu.com/ubuntu focal/universe amd64 Packages

$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ uname -r
5.8.0-63-generic

$ uname -p
x86_64
```

**Comment by Eonfge** [comment]
Wow. Thanks for this excellent bug report. I've made a pull request and I hope that it will fix the issue for everybody that uses the Flatpak version of ET Legacy

#3

**Comment by rfdparker** [comment]
Thanks @Eonfge for the quick fix! Having updated the Flatpak and deleted my user config (`~/.var/app/com.etlegacy.ETLegacy`) ‒to undo my workaround‒ I find this is resolved.

I did notice that Omni-bot does still not work on the game's first run, with the options in **Referee** » **Bots** not working and `Omni-bot not loaded` appearing in the console. Crucially, however:
- there are no `LoadLibrary` errors in the console and the console (unlike before the fix)
- it works fine on the next run
- the same behaviour is seen if the game is installed 'conventionally' (i.e. using 32-bit installer on 64-bit OS rather than Flatpak) so that's not an issue specific to this Flatpak but rather an upstream issue

**Comment by Eonfge** [comment]
No problem, reports like these make it easy for me to fix issues. Easy to reproduce and you already eluded to a fix.

>     * the same behaviour is seen if the game is installed 'conventionally' (i.e. using 32-bit installer on 64-bit OS rather than Flatpak) so that's not an issue specific to this Flatpak but rather an upstream issue

Could you report this upstream? Seems that it's just a minor detail, but it would be nice to get these kinds of bugs resolved.

**Comment by rfdparker** [comment]
> Could you report this upstream? Seems that it's just a minor detail, but it would be nice to get these kinds of bugs resolved.

Sure, this has been raised as etlegacy/etlegacy#1678
