### ISSUE TITLE
Project access `jackeri`

### ISSUE THREAD

**Issue by Eonfge** [flathub/com.etlegacy.ETLegacy#27]
@barthalion I wish to grant repository access to @jackeri who is an upstream developer, responsible for the latest release:
https://github.com/etlegacy/etlegacy/releases/tag/v2.81.1

@jackeri I'll gladly collaborate, and review your changes. This project is more complex than most, so I fully understand that you don't want to carry the burden alone.

**Comment by barthalion** [comment]
Sorry for the delay, I was first sick, then on holiday, and sick again. I've just sent an invite to @jackeri.

**Comment by jackeri** [comment]
Thanks, just accepted the invite 👍
