### ISSUE TITLE
Omni-bot fails to load on clean install

### ISSUE THREAD

**Issue by GeneralKenobi72** [flathub/com.etlegacy.ETLegacy#33]
Omni-bot fails to load.
## System used
Arch Linux x86_64
Kernel: 6.7.4-arch1-1

## Workaround
I thought that this issue was supposed to be fixed, but it doesn't run on current version.
Solution that worked for me is linked in following post:
```
https://github.com/flathub/com.etlegacy.ETLegacy/issues/2
```
I had to find installation directory of omni-bot mod, and type the command from linked post, for me:
```
\omnibot_path "/home/user/.cache/yay/etlegacy/src/etlegacy-v2.81.1-x86_64/legacy/omni-bot"

**Comment by Eonfge** [comment]
Uhm. Does it work now? Should I do some testing?

**Comment by GeneralKenobi72** [comment]
I am sorry for the confusion, I opened this issue on wrong repository, that's why closed the issue right away.

**Comment by Eonfge** [comment]
No problem, thanks for clearing this one up
