### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by pizzadude** [flathub/com.etlegacy.ETLegacy#6]
Version 2.78 is available
https://www.etlegacy.com/blog/et-legacy-278-released

**Comment by Eonfge** [comment]
Ow damn. Missed this one. Let's quickly get into action and see if we can release a new version

**Comment by Eonfge** [comment]
#7 should fix it! Thanks for reporting it, I'll implement a notification system later today

**Comment by pizzadude** [comment]
Thank you for the quick fix. :)
